# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('date', models.DateField(blank=True)),
                ('location', models.CharField(max_length=256)),
                ('points', models.PositiveIntegerField()),
                ('info', models.TextField(blank=True)),
                ('pic', models.ImageField(blank=True, upload_to='event_pics')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
